### ISSUE TITLE
Fix the model loading issue

### ISSUE THREAD

**Issue by WatIsDeze** [Pyramid-Apex-Games/Polyhedron#11]
As it turns out, mapmodels as well as regular models have a hard time being rendered. The problem relies in the lack of having 2 entities, we need a regular DynamicModel entity, and a MapModel entity. The latter has its reasons, which are explained best below. In other words, these two classes need to be properly implemented. While at it, try to get rid of using idx all over the place. This is annoying and slightly a bad part on their design.

> All of the shadowmaps affecting a single frame are further aggregated into one giant shadowmap atlas, currently 4096×4096 using 16bpp depth texture format. This better decouples the shadowmap generation and lighting phases and allows lookups for any number of shadowmaps to be easily performed in a single batch or many shading passes. Various types of shadowmaps are stored in the atlas: unrolled cubemap shadowmaps for point lights, a simple perspective projection for spotlights, and cascaded shadowmaps for directional sunlight.

> For cascaded shadowmaps for sunlight, Tesseract uses an enhanced parallel-split scheme with rotationally invariant world-space bounding boxes rounded to stable coordinate increments for each split as originally detailed for Dice's Frostbite engine. This allows for somewhat less waste of available shadowmap resolution than the standard view-parallel split scheme as well as combats temporally instability/shadow swim that would otherwise occur. For further information, see this page.

> "Caching is the new culling." Lights can often have large radiuses that pass through walls and other such occluders, often making occlusion culling or view-frustum culling of light volumes ineffective. As an alternative to never the less greatly reduce shadowmap rendering costs for such lights, the shadowmap atlas caches shadowmaps from frame to frame, down to the granularity of individual cubemap faces, if no moving objects are present in the shadowmap. Lights in Tesseract usually only affect static world geometry, at least when individual cubemap faces are considered, so the majority of shadowmapped lights are not more expensive than unshadowed lights, adding only the cost of the shadowmap lookup and filtering itself. To further optimize the rendering of shadows for static geometry, for each frustum of each light, an optimal mesh is generated of all triangles contained only within that frustum and omitting all backfacing triangles. To avoid moving textures around within the atlas, cached shadowmaps attempt to retain their placement from the previous frame within the atlas. To combat fragmentation, if the atlas becomes overly full, cached shadowmaps are occasionally evicted from a quadrant window of the atlas that progresses through the atlas from frame to frame 

The once ever so confusing lists, which there were two of them has been resolved. It in fact has its antique roots, which still and will come in handy to us. The PVS which plays a huge role in proper client/server model and rendering will take these into calculation.

Goal: Reimplement the 2 model entities and fix whichever engine module functions are related to it.

**Comment by WatIsDeze** [comment]
@Micha0 fixed by now, no?

**Comment by Micha0** [comment]
no

**Comment by WatIsDeze** [comment]
@Micha0 you've gotten this one done in your branch no? Because then it's basically fixed. (Not quite sure but it likely also already is in the littleVGL branche.)
